In [1]:
import mne
import numpy as np
import pandas as pd

In [2]:
data = mne.io.read_raw_gdf("data/A01T.gdf")

Extracting EDF parameters from d:\Study\GP\EEG-Motor-Imagery-classifier\data\A01T.gdf...
GDF file detected
Setting channel info structure...
Could not determine channel type of the following channels, they will be set as EEG:
EEG-Fz, EEG, EEG, EEG, EEG, EEG, EEG, EEG-C3, EEG, EEG-Cz, EEG, EEG-C4, EEG, EEG, EEG, EEG, EEG, EEG, EEG, EEG-Pz, EEG, EEG, EOG-left, EOG-central, EOG-right
Creating raw.info structure...


C:\Users\Mohamad Abo Bakr\AppData\Local\Programs\Python\Python39\lib\site-packages\mne\io\edf\edf.py:1123: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  etmode = np.fromstring(etmode, UINT8).tolist()[0]
C:\Users\Mohamad Abo Bakr\AppData\Local\Programs\Python\Python39\lib\contextlib.py:124: RuntimeWarning: Channel names are not unique, found duplicates for: {'EEG'}. Applying running numbers for duplicates.
  next(self.gen)


In [4]:
dataframe = data.to_data_frame()


In [5]:
events = mne.events_from_annotations(data)
codes = events[1]
events = events[0]
print(events, codes)
# print(dataframe)

Used Annotations descriptions: ['1023', '1072', '276', '277', '32766', '768', '769', '770', '771', '772']
[[     0      0      5]
 [     0      0      3]
 [ 29683      0      5]
 ...
 [670550      0      6]
 [670550      0      1]
 [671050      0      7]] {'1023': 1, '1072': 2, '276': 3, '277': 4, '32766': 5, '768': 6, '769': 7, '770': 8, '771': 9, '772': 10}


In [6]:
filter = np.asarray(['769', '770', '771', '772'])
lis = np.asarray([codes[i] for i in filter])

ev = events[np.in1d(events[:, 2], lis)]

x = np.zeros((288, 313, 26))
y = np.zeros(288)
for point in range(288):
  x[point] = dataframe.values[ev[point][0]:ev[point][0]+313]
  y[point] = ev[point][2] - 6
  


In [7]:
print(x.shape, y.shape)


(288, 313, 26) (288,)
